# Generated by Django 2.2 on 2020-09-13 23:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clients', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(default=' ', max_length=50)),
                ('model', models.CharField(blank=True, default=' ', max_length=50, null=True)),
                ('VIN', models.CharField(default=' ', max_length=50)),
                ('Year', models.CharField(default='0000', max_length=10)),
                ('Purchase_Date', models.DateField(default='', max_length=50)),
                ('Last_Service', models.DateField(default='', max_length=10)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
